import express from "express";
import request from "supertest";
import { beforeAll, describe, expect, it } from "vitest";
import { Prisma, Role } from "@prisma/client";
import apiRouter from "./routes";
import { notFoundHandler } from "./middleware/notFound";
import { errorHandler } from "./middleware/errorHandler";
import { prisma } from "./config/prisma";
import { hashPassword } from "./utils/password";
import { calculateLineAmount } from "./services/quotation.service";

function createTestApp() {
  const app = express();
  app.use(express.json());
  app.use("/api", apiRouter);
  app.use(notFoundHandler);
  app.use(errorHandler);
  return app;
}

const app = createTestApp();

const ADMIN_EMAIL = "admin.phase5.test@pern-erp.local";
const SALES_EMAIL = "sales.phase5.test@pern-erp.local";
const ADMIN_PASSWORD = "AdminPhase5@123456";
const SALES_PASSWORD = "SalesPhase5@123456";

async function loginAs(email: string, password: string): Promise<string> {
  const res = await request(app).post("/api/auth/login").send({ email, password });
  expect(res.status).toBe(200);
  return res.body.data.token as string;
}

describe("Phase 5 quotations", () => {
  let adminToken: string;
  let salesToken: string;
  let enquiryId: string;
  let productAId: string;
  let productBId: string;

  beforeAll(async () => {
    const [adminHash, salesHash] = await Promise.all([
      hashPassword(ADMIN_PASSWORD),
      hashPassword(SALES_PASSWORD),
    ]);

    await prisma.user.upsert({
      where: { email: ADMIN_EMAIL },
      update: { name: "Phase5 Admin", passwordHash: adminHash, role: Role.ADMIN },
      create: {
        name: "Phase5 Admin",
        email: ADMIN_EMAIL,
        passwordHash: adminHash,
        role: Role.ADMIN,
      },
    });

    await prisma.user.upsert({
      where: { email: SALES_EMAIL },
      update: {
        name: "Phase5 Sales",
        passwordHash: salesHash,
        role: Role.SALES_USER,
      },
      create: {
        name: "Phase5 Sales",
        email: SALES_EMAIL,
        passwordHash: salesHash,
        role: Role.SALES_USER,
      },
    });

    const products = await prisma.product.findMany({
      take: 2,
      orderBy: { productCode: "asc" },
      select: { id: true },
    });
    if (products.length < 2) {
      throw new Error("Phase 5 tests require at least 2 products");
    }
    productAId = products[0].id;
    productBId = products[1].id;

    const customer = await prisma.customer.create({
      data: {
        companyName: "Phase5 Quote Customer",
        contactPerson: "Quote Contact",
        mobile: "9111100000",
        email: "phase5.quote@example.com",
        city: "Pune",
      },
    });

    const enquiry = await prisma.enquiry.create({
      data: {
        enquiryNumber: `ENQ-P5-${Date.now()}`,
        customerId: customer.id,
        enquiryDate: new Date("2026-08-01"),
        requiredDate: new Date("2026-08-20"),
        notes: "Phase 5 fixture",
        status: "NEW",
        items: {
          create: [
            { productId: productAId, quantity: 10 },
            { productId: productBId, quantity: 5 },
          ],
        },
      },
    });
    enquiryId = enquiry.id;

    adminToken = await loginAs(ADMIN_EMAIL, ADMIN_PASSWORD);
    salesToken = await loginAs(SALES_EMAIL, SALES_PASSWORD);
  });

  it("authenticated user can create quotation", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 10,
            unitPrice: 100,
            discountPercent: 10,
            gstPercent: 18,
          },
        ],
      });

    expect(res.status).toBe(201);
    expect(res.body.data.id).toEqual(expect.any(String));
  });

  it("quotation number generated by backend and starts as DRAFT", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-02",
        quotationNumber: "CLIENT-FAKE",
        status: "ACCEPTED",
        items: [
          {
            productId: productAId,
            quantity: 2,
            unitPrice: 50,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });

    expect(res.status).toBe(201);
    expect(res.body.data.status).toBe("DRAFT");
    expect(res.body.data.quotationNumber).toMatch(/^QUO-\d{6}$/);
    expect(res.body.data.quotationNumber).not.toBe("CLIENT-FAKE");
  });

  it("quotation with multiple products and correct calculations", async () => {
    // Line A: qty 10 * 100 = 1000; disc 10% = 100; taxable 900; gst 18% = 162; line = 1062
    // Line B: qty 5 * 200 = 1000; disc 0; gst 18% = 180; line = 1180
    // Grand = 2242
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-03",
        grandTotal: 1,
        items: [
          {
            productId: productAId,
            quantity: 10,
            unitPrice: 100,
            discountPercent: 10,
            gstPercent: 18,
            lineAmount: 999999,
          },
          {
            productId: productBId,
            quantity: 5,
            unitPrice: 200,
            discountPercent: 0,
            gstPercent: 18,
          },
        ],
      });

    expect(res.status).toBe(201);
    expect(res.body.data.items).toHaveLength(2);
    expect(res.body.data.items[0].lineAmount).toBe("1062.00");
    expect(res.body.data.items[1].lineAmount).toBe("1180.00");
    expect(res.body.data.grandTotal).toBe("2242.00");
  });

  it("discount, GST, and grand total helpers match formula", () => {
    const line = calculateLineAmount({
      quantity: 10,
      unitPrice: new Prisma.Decimal("500"),
      discountPercent: new Prisma.Decimal("5"),
      gstPercent: new Prisma.Decimal("18"),
    });
    // base 5000; disc 250; taxable 4750; gst 855; line 5605
    expect(line.toFixed(2)).toBe("5605.00");
  });

  it("missing enquiry rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(400);
  });

  it("non-existent enquiry rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId: "missing-enquiry",
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(404);
  });

  it("empty quotation items rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [],
      });
    expect(res.status).toBe(400);
  });

  it("invalid product rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: "missing-product",
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(404);
  });

  it("quantity <= 0 rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 0,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(400);
  });

  it("negative unit price rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: -5,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(400);
  });

  it("discount > 100 and negative discount rejected", async () => {
    const over = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 101,
            gstPercent: 0,
          },
        ],
      });
    const negative = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: -1,
            gstPercent: 0,
          },
        ],
      });
    expect(over.status).toBe(400);
    expect(negative.status).toBe(400);
  });

  it("invalid GST rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: -5,
          },
        ],
      });
    expect(res.status).toBe(400);
  });

  it("duplicate product lines rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
          {
            productId: productAId,
            quantity: 2,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(400);
  });

  it("unauthorized create rejected", async () => {
    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${adminToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-01",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    expect(res.status).toBe(403);
  });

  it("unauthenticated request rejected", async () => {
    const res = await request(app).post("/api/quotations").send({
      enquiryId,
      validUntil: "2026-09-01",
      items: [
        {
          productId: productAId,
          quantity: 1,
          unitPrice: 10,
          discountPercent: 0,
          gstPercent: 0,
        },
      ],
    });
    expect(res.status).toBe(401);
  });

  it("quotation list and detail work", async () => {
    const list = await request(app)
      .get("/api/quotations")
      .set("Authorization", `Bearer ${adminToken}`);
    expect(list.status).toBe(200);
    expect(list.body.data.length).toBeGreaterThan(0);
    expect(list.body.data[0].customer).toBeDefined();
    expect(list.body.data[0].enquiry).toBeDefined();

    const id = list.body.data[0].id;
    const detail = await request(app)
      .get(`/api/quotations/${id}`)
      .set("Authorization", `Bearer ${salesToken}`);
    expect(detail.status).toBe(200);
    expect(detail.body.data.items[0].product.productCode).toEqual(expect.any(String));
  });

  it("valid status transition works and invalid is rejected", async () => {
    const created = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-10",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 25,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });

    const id = created.body.data.id;

    const sent = await request(app)
      .patch(`/api/quotations/${id}/status`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ status: "SENT" });
    expect(sent.status).toBe(200);
    expect(sent.body.data.status).toBe("SENT");

    const accepted = await request(app)
      .patch(`/api/quotations/${id}/status`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ status: "ACCEPTED" });
    expect(accepted.status).toBe(200);
    expect(accepted.body.data.status).toBe("ACCEPTED");

    const invalid = await request(app)
      .patch(`/api/quotations/${id}/status`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ status: "DRAFT" });
    expect(invalid.status).toBe(400);
  });

  it("SALES_USER cannot update quotation status", async () => {
    const created = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-11",
        items: [
          {
            productId: productBId,
            quantity: 1,
            unitPrice: 30,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });

    const res = await request(app)
      .patch(`/api/quotations/${created.body.data.id}/status`)
      .set("Authorization", `Bearer ${salesToken}`)
      .send({ status: "SENT" });

    expect(res.status).toBe(403);
  });

  it("quotation numbers are unique", async () => {
    const first = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-12",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });
    const second = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-13",
        items: [
          {
            productId: productBId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });

    expect(first.status).toBe(201);
    expect(second.status).toBe(201);
    expect(first.body.data.quotationNumber).not.toBe(
      second.body.data.quotationNumber
    );
  });

  it("failed quotation creation does not leave partial records", async () => {
    const before = await prisma.quotation.count({ where: { enquiryId } });

    const res = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-14",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
          {
            productId: "missing-product",
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });

    expect(res.status).toBe(404);
    const after = await prisma.quotation.count({ where: { enquiryId } });
    expect(after).toBe(before);
  });

  it("DRAFT cannot jump to ACCEPTED", async () => {
    const created = await request(app)
      .post("/api/quotations")
      .set("Authorization", `Bearer ${salesToken}`)
      .send({
        enquiryId,
        validUntil: "2026-09-15",
        items: [
          {
            productId: productAId,
            quantity: 1,
            unitPrice: 10,
            discountPercent: 0,
            gstPercent: 0,
          },
        ],
      });

    const res = await request(app)
      .patch(`/api/quotations/${created.body.data.id}/status`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ status: "ACCEPTED" });

    expect(res.status).toBe(400);
  });
});
